Workflow changes to IAC

diff --git a/.github/workflows/iac_workflow.yml b/.github/workflows/iac_workflow.yml
--- a/.github/workflows/iac_workflow.yml
+++ b/.github/workflows/iac_workflow.yml
@@ -51,9 +51,12 @@ jobs:
         if: steps.plan.outputs.exitcode == 1
         run: exit 1
 
+      - name: Print Terraform Plan Exit Code
+        run: echo $?
+
             #0 = Succeeded with empty diff (no changes)
             #1 = Error
             #2 = Succeeded with non-empty diff (changes present)
 
-      - name: Print Terraform Plan Exit Code
-        run: echo $?
+#       - name: Print Terraform Plan Exit Code
+ #       run: echo $?
